rexray:
    privileged: true
    restart: always
    build: .
    pid: 'host'
    ports:
      - "7979"
    volumes:
      - /etc/rexray:/etc/rexray
      - /var/lib/rexray:/var/lib/rexray:shared
      - /var/run/rexray:/var/run/rexray
      - /var/log/rexray:/var/log/rexray
      - /run/docker/plugins:/run/docker/plugins
      - /dev:/dev
    labels:
      - io.rancher.os.scope=system
      - io.rancher.scheduler.global=true
